services:
  filebrowser:
    image: filebrowser/filebrowser
    volumes:
      - images_dir:/srv
    command: filebrowser -p 80 -username=${IMAGE_USERNAME} -password=${IMAGE_PASSWORD}
  imageproxy:
    image: ghcr.io/willnorris/imageproxy
    command: imageproxy -cache memory --addr 0.0.0.0:80
  caddy:
    build: .
    volumes:
      - images_dir:/srv
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost/ || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
volumes:
  images_dir:
    external: true
