services:
  filebrowser:
    image: filebrowser/filebrowser
    volumes:
      - images_dir:/srv
    command: --port 80 --username=${IMAGE_USERNAME} --password=${IMAGE_PASSWORD} --baseurl=/admin/
  imageproxy:
    image: ghcr.io/willnorris/imageproxy
    command: -cache memory:200:8h -addr 0.0.0.0:80 -allowHosts ${IMAGE_HOST} -baseURL https://${IMAGE_HOST}/original/
  caddy:
    build: .
    depends_on:
      - filebrowser
      - imageproxy
    volumes:
      - images_dir:/srv
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost/ || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
volumes:
  images_dir:
    external: true
